dubbo:
  application: # 应用配置
    organization: lingmou # 组织名称
    group: lingmou # 组名称
    name: user # 应用名称
    module: simple # 模块名称，多个实例可以用不同的名字区分
    version: 1.0.0 # 版本号，不同版本可以共存
    environment: dev # 部署环境
    metadata-type: remote # 元数据类型，remote 表示远程，local 表示本地（默认）
    metadata-service-port: 20888 # 元数据服务端口
    metadata-service-protocol: tri # 元数据服务协议
  registries: # 注册中心
    nacos:
      protocol: nacos # 注册中心协议 nacos / apollo / zookeeper / etcd
      address: 118.25.146.1:31238
      namespace: "cui_test" # 命名空间
      group: "lingmou" # 配置组
      username: "" # 用户名（没有为空）
      password: "" # 密码（没有为空）
      use-as-config-center: true # 是否作为配置中心（nacos配置供配置中心使用，可以不用重复写）
      use-as-meta-report: true # 是否作为元数据上报（nacos配置供元数据上报使用，可以不用重复写）
  logger: # 日志配置
    level: "info"
    appender: "console"
  otel:
    tracing:
      enable: true
      exporter: jaeger # 你也可以换成 jaeger、zipkin、otlp-http、otlp-grpc
      endpoint: "http://localhost:14268/api/traces"  # exporter 的地址，stdout 不需要填
      propagator: w3c # 建议默认
      sample-mode: ratio
      sample-ratio: 1.0 # 全量采样
  protocols: # 协议配置
    tripleProtocol:
      name: tri
      port: 20000
  provider: # 服务提供者配置
    filter: "otelServerTrace,myCustomFilter,accesslog"
    services:
      UserProvider:
        interface: lingmou.simple.sdk.user.api.UserService # proto文件中定义的服务名称
